[project]
name = "calculator-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arooj Kanwal", email = "SITarooj890@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=2.2.0",
]

[project.scripts]
calculator-mcp-server = "calculator_mcp_server:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
